name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate keystore
        run: |
          keytool -genkeypair -v -keystore sblpd-release.jks \
            -alias sblpd -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "Dfkthbz_19999" \
            -keypass "Dfkthbz_19999" \
            -dname "CN=toxictrace, OU=Dev, O=Personal, L=City, S=State, C=US"
          base64 -w0 sblpd-release.jks > sblpd-release.jks.b64

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: |
            sblpd-release.jks
            sblpd-release.jks.b64
